=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module Daily
  class DeleteRecording200Response < ApiModelBase
    attr_accessor :deleted

    attr_accessor :id

    attr_accessor :s3_bucket

    attr_accessor :s3_region

    attr_accessor :s3_key

    # The storage provider the recording was written to. `aws` for Amazon S3 (including Daily's own storage), `oci` for OCI Object Storage. Returned only for recordings stored in a customer-managed bucket; absent for recordings held in Daily's own storage.
    attr_accessor :storage_provider

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'deleted' => :'deleted',
        :'id' => :'id',
        :'s3_bucket' => :'s3_bucket',
        :'s3_region' => :'s3_region',
        :'s3_key' => :'s3_key',
        :'storage_provider' => :'storage_provider'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'deleted' => :'Boolean',
        :'id' => :'String',
        :'s3_bucket' => :'String',
        :'s3_region' => :'String',
        :'s3_key' => :'String',
        :'storage_provider' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Daily::DeleteRecording200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Daily::DeleteRecording200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'deleted')
        self.deleted = attributes[:'deleted']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'s3_bucket')
        self.s3_bucket = attributes[:'s3_bucket']
      end

      if attributes.key?(:'s3_region')
        self.s3_region = attributes[:'s3_region']
      end

      if attributes.key?(:'s3_key')
        self.s3_key = attributes[:'s3_key']
      end

      if attributes.key?(:'storage_provider')
        self.storage_provider = attributes[:'storage_provider']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      storage_provider_validator = EnumAttributeValidator.new('String', ["aws", "oci", "unknown_default_open_api"])
      return false unless storage_provider_validator.valid?(@storage_provider)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] storage_provider Object to be assigned
    def storage_provider=(storage_provider)
      validator = EnumAttributeValidator.new('String', ["aws", "oci", "unknown_default_open_api"])
      unless validator.valid?(storage_provider)
        fail ArgumentError, "invalid value for \"storage_provider\", must be one of #{validator.allowable_values}."
      end
      @storage_provider = storage_provider
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          deleted == o.deleted &&
          id == o.id &&
          s3_bucket == o.s3_bucket &&
          s3_region == o.s3_region &&
          s3_key == o.s3_key &&
          storage_provider == o.storage_provider
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [deleted, id, s3_bucket, s3_region, s3_key, storage_provider].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
