=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module Daily
  # the configuration object passed to update an existing pinless or pin dial-in.
  class DomainDialinConfigUpdateReq < ApiModelBase
    # The phone number to update to the existing dial-in config, in E.164 format (e.g. \"+18058700061\"). If the same number is used by any other config then the API will fail.
    attr_accessor :phone_number

    # Update the name_prefix of an existing config.
    attr_accessor :name_prefix

    # The [HMAC signature](/guides/products/dial-in-dial-out/dialin-pinless#hmac) used to verify the webhook called to \"room_creation_api\". (only for pinless_dialin type).
    attr_accessor :hmac

    # The URL to call when a call is received on configured phoneNumber or sip_uri. (only for pinless_dialin type). flow is described [here](/guides/products/dial-in-dial-out/dialin-pinless#quick-overview)
    attr_accessor :room_creation_api

    # The URL to the hold music to play when the call is received, (only for pinless_dialin type). The hold music must be a publicly accessible URL in MP3 format. The hold music must be less than 10MB in size and less than 60 seconds in duration. In pinless_dialin, the hold music will be played twice.
    attr_accessor :hold_music_url

    attr_accessor :timeout_config

    attr_accessor :ivr_greeting

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'phone_number' => :'phone_number',
        :'name_prefix' => :'name_prefix',
        :'hmac' => :'hmac',
        :'room_creation_api' => :'room_creation_api',
        :'hold_music_url' => :'hold_music_url',
        :'timeout_config' => :'timeout_config',
        :'ivr_greeting' => :'ivr_greeting'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'phone_number' => :'String',
        :'name_prefix' => :'String',
        :'hmac' => :'String',
        :'room_creation_api' => :'String',
        :'hold_music_url' => :'String',
        :'timeout_config' => :'DomainDialinConfigCreateReqTimeoutConfig',
        :'ivr_greeting' => :'DomainDialinConfigCreateReqIvrGreeting'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Daily::DomainDialinConfigUpdateReq` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Daily::DomainDialinConfigUpdateReq`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'name_prefix')
        self.name_prefix = attributes[:'name_prefix']
      end

      if attributes.key?(:'hmac')
        self.hmac = attributes[:'hmac']
      end

      if attributes.key?(:'room_creation_api')
        self.room_creation_api = attributes[:'room_creation_api']
      end

      if attributes.key?(:'hold_music_url')
        self.hold_music_url = attributes[:'hold_music_url']
      end

      if attributes.key?(:'timeout_config')
        self.timeout_config = attributes[:'timeout_config']
      end

      if attributes.key?(:'ivr_greeting')
        self.ivr_greeting = attributes[:'ivr_greeting']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          phone_number == o.phone_number &&
          name_prefix == o.name_prefix &&
          hmac == o.hmac &&
          room_creation_api == o.room_creation_api &&
          hold_music_url == o.hold_music_url &&
          timeout_config == o.timeout_config &&
          ivr_greeting == o.ivr_greeting
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [phone_number, name_prefix, hmac, room_creation_api, hold_music_url, timeout_config, ivr_greeting].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
