=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module Daily
  class GetRecordingInfo200Response < ApiModelBase
    # A unique, opaque ID for this object. You can use this ID in API calls, and in paginated list operations.
    attr_accessor :id

    # The name of the [room](/reference/rest-api/rooms).
    attr_accessor :room_name

    # When the recording started. This is a unix timestamp (seconds since the epoch).
    attr_accessor :start_ts

    attr_accessor :status

    # The maximum number of participants that were ever in this room together during the meeting session that was recorded.
    attr_accessor :max_participants

    # How many seconds long the recording is, approximately. This property is not returned for recordings that are in-progress.
    attr_accessor :duration

    # Deprecated.
    attr_accessor :share_token

    # The S3 Key associated with this recording.
    attr_accessor :s3key

    # The meeting session ID for this recording.
    attr_accessor :mtg_session_id

    # If the recording is a raw-tracks recording, a tracks field will be provided. If role permissions have been removed, the tracks field may be null.
    attr_accessor :tracks

    # The storage provider the recording was written to. `aws` for Amazon S3 (including Daily's own storage), `oci` for OCI Object Storage.
    attr_accessor :storage_provider

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'room_name' => :'room_name',
        :'start_ts' => :'start_ts',
        :'status' => :'status',
        :'max_participants' => :'max_participants',
        :'duration' => :'duration',
        :'share_token' => :'share_token',
        :'s3key' => :'s3key',
        :'mtg_session_id' => :'mtgSessionId',
        :'tracks' => :'tracks',
        :'storage_provider' => :'storage_provider'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'room_name' => :'String',
        :'start_ts' => :'Integer',
        :'status' => :'String',
        :'max_participants' => :'Integer',
        :'duration' => :'Integer',
        :'share_token' => :'String',
        :'s3key' => :'String',
        :'mtg_session_id' => :'String',
        :'tracks' => :'Array<GetRecordingInfo200ResponseTracksInner>',
        :'storage_provider' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Daily::GetRecordingInfo200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Daily::GetRecordingInfo200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'room_name')
        self.room_name = attributes[:'room_name']
      end

      if attributes.key?(:'start_ts')
        self.start_ts = attributes[:'start_ts']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'max_participants')
        self.max_participants = attributes[:'max_participants']
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      end

      if attributes.key?(:'share_token')
        self.share_token = attributes[:'share_token']
      end

      if attributes.key?(:'s3key')
        self.s3key = attributes[:'s3key']
      end

      if attributes.key?(:'mtg_session_id')
        self.mtg_session_id = attributes[:'mtg_session_id']
      end

      if attributes.key?(:'tracks')
        if (value = attributes[:'tracks']).is_a?(Array)
          self.tracks = value
        end
      end

      if attributes.key?(:'storage_provider')
        self.storage_provider = attributes[:'storage_provider']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      status_validator = EnumAttributeValidator.new('String', ["finished", "in-progress", "canceled", "unknown_default_open_api"])
      return false unless status_validator.valid?(@status)
      storage_provider_validator = EnumAttributeValidator.new('String', ["aws", "oci", "unknown_default_open_api"])
      return false unless storage_provider_validator.valid?(@storage_provider)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["finished", "in-progress", "canceled", "unknown_default_open_api"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] storage_provider Object to be assigned
    def storage_provider=(storage_provider)
      validator = EnumAttributeValidator.new('String', ["aws", "oci", "unknown_default_open_api"])
      unless validator.valid?(storage_provider)
        fail ArgumentError, "invalid value for \"storage_provider\", must be one of #{validator.allowable_values}."
      end
      @storage_provider = storage_provider
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          room_name == o.room_name &&
          start_ts == o.start_ts &&
          status == o.status &&
          max_participants == o.max_participants &&
          duration == o.duration &&
          share_token == o.share_token &&
          s3key == o.s3key &&
          mtg_session_id == o.mtg_session_id &&
          tracks == o.tracks &&
          storage_provider == o.storage_provider
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, room_name, start_ts, status, max_participants, duration, share_token, s3key, mtg_session_id, tracks, storage_provider].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
