=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module Daily
  # The S3 bucket that Daily writes the HLS output to. Set exactly one of `path` or `path_template`.
  class RoomPropertiesStreamingEndpointsInnerHlsConfigStorage < ApiModelBase
    # The name of the S3 bucket where the HLS output will be stored.
    attr_accessor :bucket_name

    # The AWS region of the S3 bucket.
    attr_accessor :bucket_region

    # The Amazon Resource Name (ARN) of the IAM role Daily should assume to write to the S3 bucket.
    attr_accessor :assume_role_arn

    # The `s3Key` path prefix for where to store the recordings. Therefore, the final final master.m3u8 path template is `<bucket_name>/<path>/<mtgSessionId>/master.m3u8`, i.e. `hls_config['storage']['bucket_name']/hls_config['storage']['path']/<mtgSessionId>/master.m3u8`.
    attr_accessor :path

    # `path_template` is made up of a replacement string with prefixes, suffixes, or both. `path_template` without replacement string is also valid. The currently supported replacements are:   - `epoch_time`: The epoch time in seconds (optional)   - `domain_name`: Your Daily domain (optional)   - `room_name`: The name of the room which is getting recorded (optional)   - `mtg_session_id`: The ID of the meeting session which is getting recorded (optional)   - `instance_id`: The instance ID of the recording (optional)   - `live_streaming_id`: The ID of the live streaming in our DB (optional)    The restrictions for defining a recording template are as follows:   - The maximum size of the template is 1024 characters   - Each replacement parameter should be placed within a curly bracket (e.g., `{domain_name}`)   - Only alphanumeric characters `(0-9, A-Z, a-z)` and `.`, `/`, `-`, `_` are valid within the template  Examples - Example domain: \"myDomain\" - Example room: \"myRoom\" - example hls bucket: \"HLS_S3_BUCKET\"  Example 1: - Template: `my-hls-{domain_name}-{epoch_time}` - Resulting path of master.m3u8: `s3://HLS_S3_BUCKET/my-hls-myDomain-1675842936274/master.m3u8`  Example 2: - Template: `{room_name}/{instance_id}/` - Resulting path of master.m3u8: `myRoom/d529cd2f-fbcc-4fb7-b2c0-c4995b1162b6/master.m3u8`
    attr_accessor :path_template

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bucket_name' => :'bucket_name',
        :'bucket_region' => :'bucket_region',
        :'assume_role_arn' => :'assume_role_arn',
        :'path' => :'path',
        :'path_template' => :'path_template'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'bucket_name' => :'String',
        :'bucket_region' => :'String',
        :'assume_role_arn' => :'String',
        :'path' => :'String',
        :'path_template' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Daily::RoomPropertiesStreamingEndpointsInnerHlsConfigStorage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Daily::RoomPropertiesStreamingEndpointsInnerHlsConfigStorage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'bucket_name')
        self.bucket_name = attributes[:'bucket_name']
      else
        self.bucket_name = nil
      end

      if attributes.key?(:'bucket_region')
        self.bucket_region = attributes[:'bucket_region']
      else
        self.bucket_region = nil
      end

      if attributes.key?(:'assume_role_arn')
        self.assume_role_arn = attributes[:'assume_role_arn']
      else
        self.assume_role_arn = nil
      end

      if attributes.key?(:'path')
        self.path = attributes[:'path']
      end

      if attributes.key?(:'path_template')
        self.path_template = attributes[:'path_template']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @bucket_name.nil?
        invalid_properties.push('invalid value for "bucket_name", bucket_name cannot be nil.')
      end

      if @bucket_region.nil?
        invalid_properties.push('invalid value for "bucket_region", bucket_region cannot be nil.')
      end

      if @assume_role_arn.nil?
        invalid_properties.push('invalid value for "assume_role_arn", assume_role_arn cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @bucket_name.nil?
      return false if @bucket_region.nil?
      return false if @assume_role_arn.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] bucket_name Value to be assigned
    def bucket_name=(bucket_name)
      if bucket_name.nil?
        fail ArgumentError, 'bucket_name cannot be nil'
      end

      @bucket_name = bucket_name
    end

    # Custom attribute writer method with validation
    # @param [Object] bucket_region Value to be assigned
    def bucket_region=(bucket_region)
      if bucket_region.nil?
        fail ArgumentError, 'bucket_region cannot be nil'
      end

      @bucket_region = bucket_region
    end

    # Custom attribute writer method with validation
    # @param [Object] assume_role_arn Value to be assigned
    def assume_role_arn=(assume_role_arn)
      if assume_role_arn.nil?
        fail ArgumentError, 'assume_role_arn cannot be nil'
      end

      @assume_role_arn = assume_role_arn
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bucket_name == o.bucket_name &&
          bucket_region == o.bucket_region &&
          assume_role_arn == o.assume_role_arn &&
          path == o.path &&
          path_template == o.path_template
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [bucket_name, bucket_region, assume_role_arn, path, path_template].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
