=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module Daily
  # 
  class RoomDialOutSendDTMFRequest < ApiModelBase
    # The participant ID of the dialOut session
    attr_accessor :session_id

    # Combined string of DTMF tones to send (e.g., \"1234#\"). Maximum 20 characters.
    attr_accessor :tones

    # Duration in milliseconds that Daily signals for each DTMF digit. This is not the gap between digits: when several tones are sent in one request over SIP INFO, Daily waits a fixed 100ms between them and that gap is not configurable. Must be between 50 and 2000. The default duration is 500ms.
    attr_accessor :digit_duration_ms

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'session_id' => :'sessionId',
        :'tones' => :'tones',
        :'digit_duration_ms' => :'digitDurationMs'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'session_id' => :'String',
        :'tones' => :'String',
        :'digit_duration_ms' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Daily::RoomDialOutSendDTMFRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Daily::RoomDialOutSendDTMFRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'session_id')
        self.session_id = attributes[:'session_id']
      else
        self.session_id = nil
      end

      if attributes.key?(:'tones')
        self.tones = attributes[:'tones']
      else
        self.tones = nil
      end

      if attributes.key?(:'digit_duration_ms')
        self.digit_duration_ms = attributes[:'digit_duration_ms']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @session_id.nil?
        invalid_properties.push('invalid value for "session_id", session_id cannot be nil.')
      end

      if @tones.nil?
        invalid_properties.push('invalid value for "tones", tones cannot be nil.')
      end

      if !@digit_duration_ms.nil? && @digit_duration_ms > 2000
        invalid_properties.push('invalid value for "digit_duration_ms", must be smaller than or equal to 2000.')
      end

      if !@digit_duration_ms.nil? && @digit_duration_ms < 50
        invalid_properties.push('invalid value for "digit_duration_ms", must be greater than or equal to 50.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @session_id.nil?
      return false if @tones.nil?
      return false if !@digit_duration_ms.nil? && @digit_duration_ms > 2000
      return false if !@digit_duration_ms.nil? && @digit_duration_ms < 50
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] session_id Value to be assigned
    def session_id=(session_id)
      if session_id.nil?
        fail ArgumentError, 'session_id cannot be nil'
      end

      @session_id = session_id
    end

    # Custom attribute writer method with validation
    # @param [Object] tones Value to be assigned
    def tones=(tones)
      if tones.nil?
        fail ArgumentError, 'tones cannot be nil'
      end

      @tones = tones
    end

    # Custom attribute writer method with validation
    # @param [Object] digit_duration_ms Value to be assigned
    def digit_duration_ms=(digit_duration_ms)
      if digit_duration_ms.nil?
        fail ArgumentError, 'digit_duration_ms cannot be nil'
      end

      if digit_duration_ms > 2000
        fail ArgumentError, 'invalid value for "digit_duration_ms", must be smaller than or equal to 2000.'
      end

      if digit_duration_ms < 50
        fail ArgumentError, 'invalid value for "digit_duration_ms", must be greater than or equal to 50.'
      end

      @digit_duration_ms = digit_duration_ms
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          session_id == o.session_id &&
          tones == o.tones &&
          digit_duration_ms == o.digit_duration_ms
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [session_id, tones, digit_duration_ms].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
