=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module Daily
  class TranscriptionProperties < ApiModelBase
    # See Deepgram's documentation for [`language`](https://developers.deepgram.com/docs/language)
    attr_accessor :language

    # See Deepgram's documentation for [`model`](https://developers.deepgram.com/docs/model)
    attr_accessor :model

    # This field is deprecated, use `model` instead
    attr_accessor :tier

    # See Deepgram's documentation for [`profanity filter`](https://developers.deepgram.com/docs/profanity-filter)
    attr_accessor :profanity_filter

    # See Deepgram's documentation for [`punctuate`](https://developers.deepgram.com/docs/punctuation)
    attr_accessor :punctuate

    attr_accessor :endpointing

    attr_accessor :redact

    # Specify any Deepgram parameters. See Deepgram's documentation for [available streaming options](https://developers.deepgram.com/docs/features-overview)
    attr_accessor :extra

    # Whether Deepgram's raw response should be included in all transcription messages
    attr_accessor :include_raw_response

    # A developer provided ID of an instance, which is used for multi-instance transcription.
    attr_accessor :instance_id

    # A list of participant IDs to be transcribed. Only the participant IDs included in this array will be processed.
    attr_accessor :participants

    # The geographic region where transcription is processed. Set to `eu` to ensure transcription data stays within the European Union.
    attr_accessor :transcription_geo

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'language' => :'language',
        :'model' => :'model',
        :'tier' => :'tier',
        :'profanity_filter' => :'profanity_filter',
        :'punctuate' => :'punctuate',
        :'endpointing' => :'endpointing',
        :'redact' => :'redact',
        :'extra' => :'extra',
        :'include_raw_response' => :'includeRawResponse',
        :'instance_id' => :'instanceId',
        :'participants' => :'participants',
        :'transcription_geo' => :'transcription_geo'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'language' => :'String',
        :'model' => :'String',
        :'tier' => :'String',
        :'profanity_filter' => :'Boolean',
        :'punctuate' => :'Boolean',
        :'endpointing' => :'TranscriptionPropertiesEndpointing',
        :'redact' => :'TranscriptionPropertiesRedact',
        :'extra' => :'Object',
        :'include_raw_response' => :'Boolean',
        :'instance_id' => :'String',
        :'participants' => :'Array<String>',
        :'transcription_geo' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Daily::TranscriptionProperties` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Daily::TranscriptionProperties`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'tier')
        self.tier = attributes[:'tier']
      end

      if attributes.key?(:'profanity_filter')
        self.profanity_filter = attributes[:'profanity_filter']
      end

      if attributes.key?(:'punctuate')
        self.punctuate = attributes[:'punctuate']
      end

      if attributes.key?(:'endpointing')
        self.endpointing = attributes[:'endpointing']
      end

      if attributes.key?(:'redact')
        self.redact = attributes[:'redact']
      end

      if attributes.key?(:'extra')
        self.extra = attributes[:'extra']
      end

      if attributes.key?(:'include_raw_response')
        self.include_raw_response = attributes[:'include_raw_response']
      end

      if attributes.key?(:'instance_id')
        self.instance_id = attributes[:'instance_id']
      end

      if attributes.key?(:'participants')
        if (value = attributes[:'participants']).is_a?(Array)
          self.participants = value
        end
      end

      if attributes.key?(:'transcription_geo')
        self.transcription_geo = attributes[:'transcription_geo']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      transcription_geo_validator = EnumAttributeValidator.new('String', ["global", "eu", "unknown_default_open_api"])
      return false unless transcription_geo_validator.valid?(@transcription_geo)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] transcription_geo Object to be assigned
    def transcription_geo=(transcription_geo)
      validator = EnumAttributeValidator.new('String', ["global", "eu", "unknown_default_open_api"])
      unless validator.valid?(transcription_geo)
        fail ArgumentError, "invalid value for \"transcription_geo\", must be one of #{validator.allowable_values}."
      end
      @transcription_geo = transcription_geo
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          language == o.language &&
          model == o.model &&
          tier == o.tier &&
          profanity_filter == o.profanity_filter &&
          punctuate == o.punctuate &&
          endpointing == o.endpointing &&
          redact == o.redact &&
          extra == o.extra &&
          include_raw_response == o.include_raw_response &&
          instance_id == o.instance_id &&
          participants == o.participants &&
          transcription_geo == o.transcription_geo
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [language, model, tier, profanity_filter, punctuate, endpointing, redact, extra, include_raw_response, instance_id, participants, transcription_geo].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
