openapi: 3.0.0
servers:
  - url: "https://api.daily.co/v1"
info:
  description: >-
    The official library for communicating with the Daily REST API.
  version: 0.0.0
  title: Daily
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: room
    description: A Daily meeting room
paths:
  /rooms:
    post:
      tags:
        - room
      summary: Create a new room
      description: "A POST request to /rooms creates a new room."
      operationId: createRoom
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomResponse"
        "400":
          $ref: "#/components/responses/InvalidRequest"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "405":
          description: Invalid input
        "429":
          $ref: "#/components/responses/TooManyRequestsError"
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/RoomRequest"
    get:
      tags:
        - room
      summary: Get a list rooms
      description: "A GET request to /rooms returns a list of rooms."
      operationId: getRooms
      parameters:
        - in: query
          name: offset
          description: The number of items to skip before starting to collect the result set.
          schema:
            type: integer
        - in: query
          name: limit
          description: The numbers of items to return.
          schema:
            type: integer
        - in: query
          name: ending_before
          description: A cursor for use in pagination. ending_before is an object ID that defines your place in the list.
          schema:
            type: string
        - in: query
          name: starting_after
          description: A cursor for use in pagination. starting_after is an object ID that defines your place in the list.
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RoomResponse"
        "400":
          $ref: "#/components/responses/InvalidRequest"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "405":
          description: Invalid input
        "429":
          $ref: "#/components/responses/TooManyRequestsError"
      security:
        - bearerAuth: []
  "/rooms/{name}":
    delete:
      tags:
        - room
      summary: Delete room
      description: Delete a Daily room.
      operationId: deleteRoom
      parameters:
        - name: name
          in: path
          description: The room name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Room deleted successfully
          content:
            application/json:
              schema:
                title: Room deleted response
                description: Room deleted response
                type: object
                properties:
                  name:
                    type: string
                  deleted:
                    type: boolean
        "404":
          description: Room not found
          content:
            application/json:
              schema:
                title: Room not found response
                description: Room not found response
                type: object
                properties:
                  error:
                    type: string
                  info:
                    type: string
        "429":
          $ref: "#/components/responses/TooManyRequestsError"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                title: Server error response
                description: Server error response
                type: object
                properties:
                  error:
                    type: string

      security:
        - bearerAuth: []
  /meeting-tokens:
    post:
      tags:
        - meeting-tokens
      summary: Creates a meeting token
      description: "A POST request to /meeting-tokens creates a new meeting token."
      operationId: createMeetingToken
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: jwt
        "400":
          $ref: "#/components/responses/InvalidRequest"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "405":
          description: Invalid input
        "429":
          $ref: "#/components/responses/TooManyRequestsError"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                title: Server error response
                description: Server error response
                type: object
                properties:
                  error:
                    type: string
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/MeetingTokenRequest"

externalDocs:
  description: Find out more about Daily
  url: "https://docs.daily.co/reference"
components:
  requestBodies:
    RoomRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RoomRequest"
      description: A room object
    MeetingTokenRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MeetingTokenRequest"
      description: A room object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    RoomResponse:
      title: Room response object
      description: A Room where a Daily call is hosted.
      type: object
      properties:
        id:
          type: string
          format: uuidv2
        name:
          type: string
        api_created:
          type: boolean
        privacy:
          type: string
        url:
          type: string
          format: url
        created_at:
          type: string
          format: date-time
    RoomRequest:
      title: Room request object
      description: A Room where a Daily call is hosted.
      type: object
      properties:
        name:
          type: string
        privacy:
          type: string
          enum:
            - private
            - public
        properties: # Daily.co properties
          type: object
          properties:
            nbf:
              type: integer
            exp:
              type: integer
            max_participants:
              type: integer
            enable_people_ui:
              type: boolean
            enable_pip_ui:
              type: boolean
            enable_emoji_reactions:
              type: boolean
            enable_hand_raising:
              type: boolean
            enable_prejoin_ui:
              type: boolean
            enable_live_captions_ui:
              type: boolean
            enable_network_ui:
              type: boolean
            enable_noise_cancellation_ui:
              type: boolean
            enable_breakout_rooms:
              type: boolean
            enable_knocking:
              type: boolean
            enable_screenshare:
              type: boolean
            enable_video_processing_ui:
              type: boolean
            enable_chat:
              type: boolean
            start_video_off:
              type: boolean
            start_audio_off:
              type: boolean
            owner_only_broadcast:
              type: boolean
            enable_recording:
              type: string
              enum:
                - local
                - cloud
                - raw-tracks
            eject_at_room_exp:
              type: boolean
            eject_after_elapsed:
              type: boolean
            enable_advanced_chat:
              type: boolean
            enable_hidden_participants:
              type: boolean
            enable_mesh_sfu:
              type: boolean
            sfu_switchover:
              type: number
            experimental_optimize_large_calls:
              type: boolean
            lang:
              type: string
              enum:
                - "de"
                - "en"
                - "es"
                - "fi"
                - "fr"
                - "it"
                - "jp"
                - "ka"
                - "nl"
                - "no"
                - "pt"
                - "pt-BR"
                - "pl"
                - "ru"
                - "sv"
                - "tr"
                - "user"
            meeting_join_hook:
              type: string
            geo:
              type: string
    MeetingTokenRequest:
      title: Meeting token request
      description: Meeting token request
      type: object
      properties:
        properties:
          type: object
          properties:
            room_name:
              type: string
            eject_at_token_exp:
              type: boolean
            nbf:
              type: integer
            exp:
              type: integer
            is_owner:
              type: boolean
            user_name:
              type: string
            user_id:
              type: string
            enable_screenshare:
              type: boolean
            start_video_off:
              type: boolean
            start_audio_off:
              type: boolean
            enable_recording:
              type: string
              enum:
                - local
                - cloud
                - raw-tracks
            enable_prejoin_ui:
              type: boolean
            enable_live_captions_ui:
              type: boolean
            enable_recording_ui:
              type: boolean
            enable_terse_logging:
              type: boolean
            auto_start_transcription:
              type: boolean
            close_tab_on_exit:
              type: boolean
            redirect_on_meeting_exit:
              type: string
            lang:
              type: string
              enum:
                - "de"
                - "en"
                - "es"
                - "fi"
                - "fr"
                - "it"
                - "jp"
                - "ka"
                - "nl"
                - "no"
                - "pt"
                - "pt-BR"
                - "pl"
                - "ru"
                - "sv"
                - "tr"
                - "user"
            permissions:
              type: object
              properties:
                has_presence:
                  type: boolean
                can_send:
                  oneOf:
                    - type: array
                      items:
                        type: string
                        enum: ["video", "audio", "screenVideo", "screenAudio"]
                    - type: boolean
                can_admin:
                  oneOf:
                    - type: array
                      items:
                        type: string
                        enum: ["participants", "streaming", "transcription"]
                    - type: boolean
          required:
            - room_name

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    TooManyRequestsError:
      description: Too many requests
    InvalidRequest:
      description: Invalid request
