=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Daily::BatchRoomsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BatchRoomsApi' do
  before do
    # run before each test
    @api_instance = Daily::BatchRoomsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BatchRoomsApi' do
    it 'should create an instance of BatchRoomsApi' do
      expect(@api_instance).to be_instance_of(Daily::BatchRoomsApi)
    end
  end

  # unit tests for batch_room_create
  # /batch/rooms
  # Create rooms in bulk
  # @param [Hash] opts the optional parameters
  # @option opts [BatchRoomCreateRequest] :batch_room_create_request 
  # @return [Array<RoomsRoomNameGetRes>]
  describe 'batch_room_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for batch_room_delete
  # /batch/rooms
  # Delete rooms in bulk
  # @param [Hash] opts the optional parameters
  # @return [BatchRoomDelete200Response]
  describe 'batch_room_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
