=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Daily::DialinApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DialinApi' do
  before do
    # run before each test
    @api_instance = Daily::DialinApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DialinApi' do
    it 'should create an instance of DialinApi' do
      expect(@api_instance).to be_instance_of(Daily::DialinApi)
    end
  end

  # unit tests for pinless_call_update
  # /dialin/pinlessCallUpdate
  # Direct a SIP or PSTN call on hold to a specified SIP URI associated to a Daily Room.
  # @param [Hash] opts the optional parameters
  # @option opts [PinlessCallUpdateRequest] :pinless_call_update_request 
  # @return [nil]
  describe 'pinless_call_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
