=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Daily::MeetingTokensApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MeetingTokensApi' do
  before do
    # run before each test
    @api_instance = Daily::MeetingTokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MeetingTokensApi' do
    it 'should create an instance of MeetingTokensApi' do
      expect(@api_instance).to be_instance_of(Daily::MeetingTokensApi)
    end
  end

  # unit tests for create_meeting_token
  # meeting-tokens
  # Create a meeting token
  # @param [Hash] opts the optional parameters
  # @option opts [CreateMeetingTokenRequest] :create_meeting_token_request 
  # @return [CreateMeetingToken200Response]
  describe 'create_meeting_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate_meeting_token
  # meeting-tokens/:meeting_token
  # Validate meeting tokens
  # @param meeting_token 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :ignore_nbf Ignore the &#x60;nbf&#x60; in a JWT, if given
  # @return [ValidateMeetingToken200Response]
  describe 'validate_meeting_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
