=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Daily::PhoneNumbersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PhoneNumbersApi' do
  before do
    # run before each test
    @api_instance = Daily::PhoneNumbersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhoneNumbersApi' do
    it 'should create an instance of PhoneNumbersApi' do
      expect(@api_instance).to be_instance_of(Daily::PhoneNumbersApi)
    end
  end

  # unit tests for buy_phone_number
  # /buy-phone-number
  # This will buy a phone number. In the POST request you can either provide the phone number you want to buy, or leave it empty. If the specified &#x60;number&#x60; is still available, it will be bought or the API will return a failure. Alternatively, if you skipped the &#x60;number&#x60; field, a random phone number from California (CA) will be bought.
  # @param [Hash] opts the optional parameters
  # @option opts [BuyPhoneNumberRequest] :buy_phone_number_request 
  # @return [Object]
  describe 'buy_phone_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_available_numbers
  # /list-available-numbers
  # Search for available phone numbers to purchase
  # @param [Hash] opts the optional parameters
  # @option opts [String] :areacode An areacode to search within.
  # @option opts [String] :region A region or state to search within. Must be an ISO 3166-2 alpha-2 code, i.e. CA for California. Cannot be used in combination with areacode.
  # @option opts [String] :city A specific City to search within. Example, New York. The string must be url encoded because it is a url parameter. Must be used in combination with region. Cannot be used in combination with areacode, starts_with, contains, or ends_with.
  # @option opts [String] :contains A string of 3 to 7 digits that should appear somewhere in the number.
  # @option opts [String] :starts_with A string of 3 to 7 digits that should be used as the start of a number. Cannot be used in combination with contains or ends_with.
  # @option opts [String] :ends_with A string of 3 to 7 digits that should be used as the end of a number. Cannot be used in combination with starts_with or contains.
  # @return [nil]
  describe 'list_available_numbers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for purchased_phone_nunbers
  # /purchased-phone-numbers
  # List the purchased phone numbers for this domain
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'purchased_phone_nunbers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for release_phone_number
  # release-phone-number/:id
  # Release a purchased number. The number is referenced by its id. A number cannot be deleted within the 14 days of purchase. Calling this API before this period expires results in an error.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'release_phone_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
