=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Daily::RecordingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecordingsApi' do
  before do
    # run before each test
    @api_instance = Daily::RecordingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecordingsApi' do
    it 'should create an instance of RecordingsApi' do
      expect(@api_instance).to be_instance_of(Daily::RecordingsApi)
    end
  end

  # unit tests for delete_recording
  # recordings/:id
  # Delete a recording
  # @param recording_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_recording test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_recording_info
  # recordings/:id
  # Get info about a recording
  # @param recording_id 
  # @param [Hash] opts the optional parameters
  # @return [GetRecordingInfo200Response]
  describe 'get_recording_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_recording_link
  # recordings/:id/access-link
  # Generate an access link for a recording
  # @param recording_id 
  # @param [Hash] opts the optional parameters
  # @return [GetRecordingLink200Response]
  describe 'get_recording_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_recordings
  # /recordings
  # List recordings
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :ending_before 
  # @option opts [String] :starting_after 
  # @option opts [String] :room_name 
  # @return [ListRecordings200Response]
  describe 'list_recordings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
