=begin
#Daily

#The official library for communicating with the Daily REST API.

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Daily::MeetingTokenRequestPropertiesPermissions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Daily::MeetingTokenRequestPropertiesPermissions do
  let(:instance) { Daily::MeetingTokenRequestPropertiesPermissions.new }

  describe 'test an instance of MeetingTokenRequestPropertiesPermissions' do
    it 'should create an instance of MeetingTokenRequestPropertiesPermissions' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Daily::MeetingTokenRequestPropertiesPermissions)
    end
  end

  describe 'test attribute "has_presence"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "can_send"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "can_admin"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
