=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Daily::RoomProperties
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Daily::RoomProperties do
  let(:instance) { Daily::RoomProperties.new }

  describe 'test an instance of RoomProperties' do
    it 'should create an instance of RoomProperties' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Daily::RoomProperties)
    end
  end

  describe 'test attribute "nbf"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "exp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "max_participants"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_people_ui"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_pip_ui"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_emoji_reactions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_hand_raising"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_prejoin_ui"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_network_ui"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_noise_cancellation_ui"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_breakout_rooms"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_knocking"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_screenshare"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_video_processing_ui"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_chat"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_video_off"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_audio_off"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "owner_only_broadcast"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_recording"' do
    it 'is not sent when unset' do
      expect(Daily::RoomProperties.new.to_hash).not_to have_key(:enable_recording)
    end

    it 'is sent when set' do
      expect(Daily::RoomProperties.new(enable_recording: 'cloud').to_hash[:enable_recording]).to eq('cloud')
    end

    # Since 1.1.0 the spec marks enable_recording as nullable, so an explicit
    # nil is sent as JSON null (same as geo). Leaving it unset sends nothing.
    it 'is sent as null when set to nil on purpose' do
      hash = Daily::RoomProperties.new(enable_recording: nil).to_hash
      expect(hash).to have_key(:enable_recording)
      expect(hash[:enable_recording]).to be_nil
    end
  end

  describe 'test attribute "eject_at_room_exp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "eject_after_elapsed"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_advanced_chat"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_hidden_participants"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_mesh_sfu"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "sfu_switchover"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "experimental_optimize_large_calls"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "lang"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["de", "en", "es", "fi", "fr", "it", "jp", "ka", "nl", "no", "pt", "pt-BR", "pl", "ru", "sv", "tr", "user"])
      # validator.allowable_values.each do |value|
      #   expect { instance.lang = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "meeting_join_hook"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "geo"' do
    it 'is not sent when unset' do
      expect(Daily::RoomProperties.new.to_hash).not_to have_key(:geo)
    end

    it 'is sent when set' do
      expect(Daily::RoomProperties.new(geo: 'eu-central-1').to_hash[:geo]).to eq('eu-central-1')
    end

    it 'is sent as null when set to nil, so a saved value can be cleared' do
      hash = Daily::RoomProperties.new(geo: nil).to_hash
      expect(hash).to have_key(:geo)
      expect(hash[:geo]).to be_nil
    end
  end

  describe 'test attribute "rtmp_geo"' do
    it 'is not sent when unset' do
      expect(Daily::RoomProperties.new.to_hash).not_to have_key(:rtmp_geo)
    end

    it 'is sent when set' do
      expect(Daily::RoomProperties.new(rtmp_geo: 'us-west-2').to_hash[:rtmp_geo]).to eq('us-west-2')
    end

    it 'is sent as null when set to nil, so a saved value can be cleared' do
      hash = Daily::RoomProperties.new(rtmp_geo: nil).to_hash
      expect(hash).to have_key(:rtmp_geo)
      expect(hash[:rtmp_geo]).to be_nil
    end
  end

  describe 'test attribute "disable_rtmp_geo_fallback"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "recordings_bucket"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_terse_logging"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "auto_transcription_settings"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enable_transcription_storage"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "transcription_bucket"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "recordings_template"' do
    it 'is not sent when unset' do
      expect(Daily::RoomProperties.new.to_hash).not_to have_key(:recordings_template)
    end

    it 'is sent when set' do
      expect(Daily::RoomProperties.new(recordings_template: '{room_name}/{epoch_time}.mp4').to_hash[:recordings_template]).to eq('{room_name}/{epoch_time}.mp4')
    end

    it 'is sent as null when set to nil, so a saved value can be cleared' do
      hash = Daily::RoomProperties.new(recordings_template: nil).to_hash
      expect(hash).to have_key(:recordings_template)
      expect(hash[:recordings_template]).to be_nil
    end
  end

  describe 'test attribute "streaming_endpoints"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "permissions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
