=begin
#Daily API

#The Daily REST API offers the ability to manage the following:  - Overall Domain Configuration - Individual Room creation and config management  - Meeting token creation and validation - Recording and compositing management  - Meeting analytics - Logs and metrics - Real-time presence  Please reach out to help@daily.co if we can help with anything

The version of the OpenAPI document: 1.1.1
Contact: help@daily.co
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'cgi'

module Daily
  class DialinApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # /sip-clients
    # Register a plain SIP client for your domain. Returns the client's SIP URI and a generated `password`, shown ONCE and never returned again. Provide a `username` (a room-style name, optionally suffixed with `.<number>`); supply your own `password` or let one be generated. An optional `expires_in_seconds` sets a TTL after which the client is removed automatically - omit it for a long-lived client. Subject to a per-domain client limit.
    # @param create_sip_client_request [CreateSipClientRequest] 
    # @param [Hash] opts the optional parameters
    # @return [CreateSipClient200Response]
    def create_sip_client(create_sip_client_request, opts = {})
      data, _status_code, _headers = create_sip_client_with_http_info(create_sip_client_request, opts)
      data
    end

    # /sip-clients
    # Register a plain SIP client for your domain. Returns the client&#39;s SIP URI and a generated &#x60;password&#x60;, shown ONCE and never returned again. Provide a &#x60;username&#x60; (a room-style name, optionally suffixed with &#x60;.&lt;number&gt;&#x60;); supply your own &#x60;password&#x60; or let one be generated. An optional &#x60;expires_in_seconds&#x60; sets a TTL after which the client is removed automatically - omit it for a long-lived client. Subject to a per-domain client limit.
    # @param create_sip_client_request [CreateSipClientRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(CreateSipClient200Response, Integer, Hash)>] CreateSipClient200Response data, response status code and response headers
    def create_sip_client_with_http_info(create_sip_client_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.create_sip_client ...'
      end
      # verify the required parameter 'create_sip_client_request' is set
      if @api_client.config.client_side_validation && create_sip_client_request.nil?
        fail ArgumentError, "Missing the required parameter 'create_sip_client_request' when calling DialinApi.create_sip_client"
      end
      # resource path
      local_var_path = '/sip-clients'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_sip_client_request)

      # return_type
      return_type = opts[:debug_return_type] || 'CreateSipClient200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.create_sip_client",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#create_sip_client\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-trunk
    # Create a SIP trunk for your domain. Returns the `sip_uri` to point your carrier at, plus the generated `hmac`. `notification.webhook_url` is required and must be LIVE: create sends a signed one-shot `sip_trunk.test` POST that must return 2xx, or the create fails with 400. A trunk must be gated by `allowed_ips`/`credential` or explicitly `is_open: true`.
    # @param create_sip_trunk_request [CreateSipTrunkRequest] 
    # @param [Hash] opts the optional parameters
    # @return [CreateSipTrunk200Response]
    def create_sip_trunk(create_sip_trunk_request, opts = {})
      data, _status_code, _headers = create_sip_trunk_with_http_info(create_sip_trunk_request, opts)
      data
    end

    # /sip-trunk
    # Create a SIP trunk for your domain. Returns the &#x60;sip_uri&#x60; to point your carrier at, plus the generated &#x60;hmac&#x60;. &#x60;notification.webhook_url&#x60; is required and must be LIVE: create sends a signed one-shot &#x60;sip_trunk.test&#x60; POST that must return 2xx, or the create fails with 400. A trunk must be gated by &#x60;allowed_ips&#x60;/&#x60;credential&#x60; or explicitly &#x60;is_open: true&#x60;.
    # @param create_sip_trunk_request [CreateSipTrunkRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(CreateSipTrunk200Response, Integer, Hash)>] CreateSipTrunk200Response data, response status code and response headers
    def create_sip_trunk_with_http_info(create_sip_trunk_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.create_sip_trunk ...'
      end
      # verify the required parameter 'create_sip_trunk_request' is set
      if @api_client.config.client_side_validation && create_sip_trunk_request.nil?
        fail ArgumentError, "Missing the required parameter 'create_sip_trunk_request' when calling DialinApi.create_sip_trunk"
      end
      # resource path
      local_var_path = '/sip-trunk'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_sip_trunk_request)

      # return_type
      return_type = opts[:debug_return_type] || 'CreateSipTrunk200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.create_sip_trunk",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#create_sip_trunk\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-clients/{username}
    # Delete a SIP client. After deletion it can no longer register or place calls.
    # @param username [String] 
    # @param [Hash] opts the optional parameters
    # @return [DeleteSipClient200Response]
    def delete_sip_client(username, opts = {})
      data, _status_code, _headers = delete_sip_client_with_http_info(username, opts)
      data
    end

    # /sip-clients/{username}
    # Delete a SIP client. After deletion it can no longer register or place calls.
    # @param username [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(DeleteSipClient200Response, Integer, Hash)>] DeleteSipClient200Response data, response status code and response headers
    def delete_sip_client_with_http_info(username, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.delete_sip_client ...'
      end
      # verify the required parameter 'username' is set
      if @api_client.config.client_side_validation && username.nil?
        fail ArgumentError, "Missing the required parameter 'username' when calling DialinApi.delete_sip_client"
      end
      # resource path
      local_var_path = '/sip-clients/{username}'.sub('{username}', CGI.escape(username.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'DeleteSipClient200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.delete_sip_client",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#delete_sip_client\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-trunk/{id}
    # Delete a SIP trunk (and its Kamailio credential, if any).
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_sip_trunk(id, opts = {})
      delete_sip_trunk_with_http_info(id, opts)
      nil
    end

    # /sip-trunk/{id}
    # Delete a SIP trunk (and its Kamailio credential, if any).
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_sip_trunk_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.delete_sip_trunk ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling DialinApi.delete_sip_trunk"
      end
      # resource path
      local_var_path = '/sip-trunk/{id}'.sub('{id}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.delete_sip_trunk",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#delete_sip_trunk\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-clients/{username}
    # Fetch one SIP client by username. The password is never returned.
    # @param username [String] 
    # @param [Hash] opts the optional parameters
    # @return [ListSipClients200ResponseSipClientsInner]
    def get_sip_client(username, opts = {})
      data, _status_code, _headers = get_sip_client_with_http_info(username, opts)
      data
    end

    # /sip-clients/{username}
    # Fetch one SIP client by username. The password is never returned.
    # @param username [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ListSipClients200ResponseSipClientsInner, Integer, Hash)>] ListSipClients200ResponseSipClientsInner data, response status code and response headers
    def get_sip_client_with_http_info(username, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.get_sip_client ...'
      end
      # verify the required parameter 'username' is set
      if @api_client.config.client_side_validation && username.nil?
        fail ArgumentError, "Missing the required parameter 'username' when calling DialinApi.get_sip_client"
      end
      # resource path
      local_var_path = '/sip-clients/{username}'.sub('{username}', CGI.escape(username.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListSipClients200ResponseSipClientsInner'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.get_sip_client",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#get_sip_client\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-trunk/{id}
    # Fetch one SIP trunk by id.
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [ListSipTrunks200ResponseDataInner]
    def get_sip_trunk(id, opts = {})
      data, _status_code, _headers = get_sip_trunk_with_http_info(id, opts)
      data
    end

    # /sip-trunk/{id}
    # Fetch one SIP trunk by id.
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ListSipTrunks200ResponseDataInner, Integer, Hash)>] ListSipTrunks200ResponseDataInner data, response status code and response headers
    def get_sip_trunk_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.get_sip_trunk ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling DialinApi.get_sip_trunk"
      end
      # resource path
      local_var_path = '/sip-trunk/{id}'.sub('{id}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListSipTrunks200ResponseDataInner'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.get_sip_trunk",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#get_sip_trunk\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-clients
    # List the SIP clients registered for your domain (paginated). Passwords are never returned.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Max results (1-100, default 50).
    # @option opts [Integer] :offset Number of results to skip (default 0).
    # @return [ListSipClients200Response]
    def list_sip_clients(opts = {})
      data, _status_code, _headers = list_sip_clients_with_http_info(opts)
      data
    end

    # /sip-clients
    # List the SIP clients registered for your domain (paginated). Passwords are never returned.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Max results (1-100, default 50).
    # @option opts [Integer] :offset Number of results to skip (default 0).
    # @return [Array<(ListSipClients200Response, Integer, Hash)>] ListSipClients200Response data, response status code and response headers
    def list_sip_clients_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.list_sip_clients ...'
      end
      # resource path
      local_var_path = '/sip-clients'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListSipClients200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.list_sip_clients",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#list_sip_clients\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-trunk
    # List the SIP trunks for your domain (paginated).
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Max results (1-100, default 20).
    # @option opts [String] :starting_after 
    # @option opts [String] :ending_before 
    # @option opts [String] :trunk_name Substring match.
    # @option opts [String] :description Substring match.
    # @option opts [Boolean] :enabled 
    # @return [ListSipTrunks200Response]
    def list_sip_trunks(opts = {})
      data, _status_code, _headers = list_sip_trunks_with_http_info(opts)
      data
    end

    # /sip-trunk
    # List the SIP trunks for your domain (paginated).
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Max results (1-100, default 20).
    # @option opts [String] :starting_after 
    # @option opts [String] :ending_before 
    # @option opts [String] :trunk_name Substring match.
    # @option opts [String] :description Substring match.
    # @option opts [Boolean] :enabled 
    # @return [Array<(ListSipTrunks200Response, Integer, Hash)>] ListSipTrunks200Response data, response status code and response headers
    def list_sip_trunks_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.list_sip_trunks ...'
      end
      # resource path
      local_var_path = '/sip-trunk'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'starting_after'] = opts[:'starting_after'] if !opts[:'starting_after'].nil?
      query_params[:'ending_before'] = opts[:'ending_before'] if !opts[:'ending_before'].nil?
      query_params[:'trunk_name'] = opts[:'trunk_name'] if !opts[:'trunk_name'].nil?
      query_params[:'description'] = opts[:'description'] if !opts[:'description'].nil?
      query_params[:'enabled'] = opts[:'enabled'] if !opts[:'enabled'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListSipTrunks200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.list_sip_trunks",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#list_sip_trunks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /dialin/pinlessCallUpdate
    # Direct a SIP or PSTN call on hold to a specified SIP URI associated to a Daily Room.
    # @param [Hash] opts the optional parameters
    # @option opts [PinlessCallUpdateRequest] :pinless_call_update_request 
    # @return [nil]
    def pinless_call_update(opts = {})
      pinless_call_update_with_http_info(opts)
      nil
    end

    # /dialin/pinlessCallUpdate
    # Direct a SIP or PSTN call on hold to a specified SIP URI associated to a Daily Room.
    # @param [Hash] opts the optional parameters
    # @option opts [PinlessCallUpdateRequest] :pinless_call_update_request 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def pinless_call_update_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.pinless_call_update ...'
      end
      # resource path
      local_var_path = '/dialin/pinlessCallUpdate'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'pinless_call_update_request'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.pinless_call_update",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#pinless_call_update\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-clients/{username}/rotate
    # Rotate a SIP client's password. Supply a new `password` or let one be generated; the new password is returned ONCE. The client's SIP URI and expiry are unchanged.
    # @param username [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [RotateSipClientRequest] :rotate_sip_client_request 
    # @return [RotateSipClient200Response]
    def rotate_sip_client(username, opts = {})
      data, _status_code, _headers = rotate_sip_client_with_http_info(username, opts)
      data
    end

    # /sip-clients/{username}/rotate
    # Rotate a SIP client&#39;s password. Supply a new &#x60;password&#x60; or let one be generated; the new password is returned ONCE. The client&#39;s SIP URI and expiry are unchanged.
    # @param username [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [RotateSipClientRequest] :rotate_sip_client_request 
    # @return [Array<(RotateSipClient200Response, Integer, Hash)>] RotateSipClient200Response data, response status code and response headers
    def rotate_sip_client_with_http_info(username, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.rotate_sip_client ...'
      end
      # verify the required parameter 'username' is set
      if @api_client.config.client_side_validation && username.nil?
        fail ArgumentError, "Missing the required parameter 'username' when calling DialinApi.rotate_sip_client"
      end
      # resource path
      local_var_path = '/sip-clients/{username}/rotate'.sub('{username}', CGI.escape(username.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'rotate_sip_client_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'RotateSipClient200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.rotate_sip_client",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#rotate_sip_client\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # /sip-trunk/{id}
    # Update a SIP trunk (partial overlay). `trunk_name` is immutable. In `notification`, `hmac: null` ROTATES the secret (Daily regenerates a fresh one); a value sets it; omit to keep the current one. Any update touching `notification` re-sends the signed `sip_trunk.test` probe (with the final hmac) - the endpoint must return 2xx. `trunk_config.credential: null` clears the credential. Admission must remain valid (gated XOR is_open).
    # @param id [String] 
    # @param update_sip_trunk_request [UpdateSipTrunkRequest] 
    # @param [Hash] opts the optional parameters
    # @return [ListSipTrunks200ResponseDataInner]
    def update_sip_trunk(id, update_sip_trunk_request, opts = {})
      data, _status_code, _headers = update_sip_trunk_with_http_info(id, update_sip_trunk_request, opts)
      data
    end

    # /sip-trunk/{id}
    # Update a SIP trunk (partial overlay). &#x60;trunk_name&#x60; is immutable. In &#x60;notification&#x60;, &#x60;hmac: null&#x60; ROTATES the secret (Daily regenerates a fresh one); a value sets it; omit to keep the current one. Any update touching &#x60;notification&#x60; re-sends the signed &#x60;sip_trunk.test&#x60; probe (with the final hmac) - the endpoint must return 2xx. &#x60;trunk_config.credential: null&#x60; clears the credential. Admission must remain valid (gated XOR is_open).
    # @param id [String] 
    # @param update_sip_trunk_request [UpdateSipTrunkRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ListSipTrunks200ResponseDataInner, Integer, Hash)>] ListSipTrunks200ResponseDataInner data, response status code and response headers
    def update_sip_trunk_with_http_info(id, update_sip_trunk_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DialinApi.update_sip_trunk ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling DialinApi.update_sip_trunk"
      end
      # verify the required parameter 'update_sip_trunk_request' is set
      if @api_client.config.client_side_validation && update_sip_trunk_request.nil?
        fail ArgumentError, "Missing the required parameter 'update_sip_trunk_request' when calling DialinApi.update_sip_trunk"
      end
      # resource path
      local_var_path = '/sip-trunk/{id}'.sub('{id}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(update_sip_trunk_request)

      # return_type
      return_type = opts[:debug_return_type] || 'ListSipTrunks200ResponseDataInner'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"DialinApi.update_sip_trunk",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DialinApi#update_sip_trunk\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
