name: Ruby CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0", "3.1"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Ruby version
        run: ruby -v

      - name: Bundle config
        run: bundle config set --local deployment true

      - name: Bundle install
        run: bundle install -j $(nproc)

      - name: Run RSpec
        run: bundle exec rspec

      - name: Build the gem
        run: bundle exec rake build

      - name: Install the gem
        run: bundle exec rake install

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: pkg/*.gem
